version: '3.5'

services:
  kaira-web:
    container_name: kaira-web
    build:
      context: ./etc/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - kaira-be
    networks:
      - kaira-network

  kaira-be:
    container_name: kaira-be
    build:
      context: etc/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=kaira

    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - kaira-network

networks:
  kaira-network:
    external: true
